version: '3'
services: 
  onetimesecret: 
    image: "onetimesecret"
    ports: 
      - "80:7143"
    links:
      - "redis:redis"
    environment:
      - OTS_DOMAIN=onetimesecret.civisanalytics.com
      - OTS_HOST=civisanalytics.com
      - OTS_SSL=true
  redis:
    image: "redis:3.2"
    ports: 
      - "6379:6379"